### ISSUE TITLE
cannot parse XML as table

### ISSUE THREAD

**Issue by VladimirAlexiev** [TriplyDB/Yasgui#133]
Hi @LaurensRietveld !
* http://data.culture.fr/thesaurus/sparql supports only GET, returns only XML (disregards Accept header), and doesn't return the precise Content-Type expected.
* I used the old yasgui (http://yasgui.org/short/-NJ26ximw) to display a simple table from that endpoint.
* I tried with the new yasgui (https://api.triplydb.com/s/mIXe4sbf) but it displays raw XML instead of a table. Maybe it's looking for the precise Content-Type whereas the server returns `application/xml`?

```
$ curl -I  "http://data.culture.fr/thesaurus/sparql?query=PREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0D%0Aselect+%3Fprop+%3Fdomain+%28count%28*%29+as+%3Fc%29+%7B%0D%0A++values+%3Fp+%7Bskos%3ArelatedMatch+skos%3AcloseMatch+skos%3AexactMatch%7D%0D%0A++%3Fx+skos%3AinScheme+%3Chttp%3A%2F%2Fdata.culture.fr%2Fthesaurus%2Fresource%2Fark%3A%2F67717%2FT69%3E%3B+%3Fp+%3Fo.%0D%0A++bind%28replace%28str%28%3Fp%29%2C%22%5E.*%23%28.*%29Match%24%22%2C%22%241%22%29+as+%3Fprop%29%0D%0A++bind%28replace%28str%28%3Fo%29%2C%22%5E%28.*%29%2F.*%24%22%2C%22%241%22%29+as+%3Fdomain%29%0D%0A%7D+group+by+%3Fprop+%3Fdomain+order+by+%3Fdomain+%3Fprop%0D%0A"
HTTP/1.1 200 OK
Date: Thu, 09 Jan 2020 13:59:18 GMT
Content-Type: application/xml
```

**Comment by LaurensRietveld** [comment]
Thanks a lot, before migrating, I'll make sure to have fixed this :+1:

**Comment by LaurensRietveld** [comment]
This is now fixed

**Comment by VladimirAlexiev** [comment]
@LaurensRietveld the link https://api.triplydb.com/s/mIXe4sbf still shows the same, I guess the fix is not yet deployed?

**Comment by LaurensRietveld** [comment]
This is indeed a deployment issue. It is deployed on the unstable yasgui version, so you can test over there as well: https://api.triplydb.com/s/NIxg1CiN

(I expect the deployment issue of yasgui.triply.cc to be fixed later today btw)
